<instance id="test.1000000" docsrc = "BNC/A04">
<answer instance="test.1000001" senseid="test%container"/>
<context>
One story about his teaching is that a new student would be told to observe a fish in a  <head>test</head> . 
</context>
</instance>

<instance id="test.1000001" docsrc = "BNC/A04">
<answer instance="test.1000002" senseid="test%booper"/>
<context>
Two story about his teaching is that a new student would be told to observe a fish in a  <head>test</head> . 
</context>
</instance>


<instance id="test.1000002" docsrc = "BNC/A04">
<answer instance="test.1000003" senseid="test%booper"/>
<context>
Two story about his teaching is that a new student would be told to observe a fish in a  <head>test</head> . 
</context>
</instance>


<instance id="test.1000003" docsrc = "BNC/A04">
<answer instance="test.1000004" senseid="test%booper"/>
<context>
Two story about his teaching is that a new student would be told to observe a fish in a  <head>test</head> . 
</context>
</instance>

<instance id="test.1000004" docsrc = "BNC/A04">
<answer instance="test.1000005" senseid="test%container"/>
<context>
One story about his teaching is that a new student would be told to observe a fish in a  <head>test</head> . 
</context>
</instance>

<instance id="test.1000005" docsrc = "BNC/A04">
<answer instance="test.1000006" senseid="test%container"/>
<context>
One story about his teaching is that a new student would be told to observe a fish in a  <head>test</head> . 
</context>
</instance>





