<instance id="test.1000000" docsrc = "BNC/A04">
<answer instance="test.1000000" senseid="test%container"/>
<context>
One story about his teaching is that a new student would be told to observe a fish in a  <head>test</head> . 
</context>
</instance>

<instance id="test.1000000" docsrc = "BNC/A04">
<answer instance="test.1000000" senseid="test%booper"/>
<context>
One story about his teaching is that a new student would be told to observe a fish in a  <head>test</head> . 
</context>
</instance>


<instance id="test.1000000" docsrc = "BNC/A04">
<answer instance="test.1000000" senseid="test%booper"/>
<context>
One story about his teaching is that a new student would be told to observe a fish in a  <head>test</head> . 
</context>
</instance>


<instance id="test.1000000" docsrc = "BNC/A04">
<answer instance="test.1000000" senseid="test%booper"/>
<context>
One story about his teaching is that a new student would be told to observe a fish in a  <head>test</head> . 
</context>
</instance>

<instance id="test.1000000" docsrc = "BNC/A04">
<answer instance="test.1000000" senseid="test%container"/>
<context>
One story about his teaching is that a new student would be told to observe a fish in a  <head>test</head> . 
</context>
</instance>

<instance id="test.1000000" docsrc = "BNC/A04">
<answer instance="test.1000000" senseid="test%container"/>
<context>
One story about his teaching is that a new student would be told to observe a fish in a  <head>test</head> . 
</context>
</instance>





